//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudžba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudžba()
        {
            this.Narudžba_Dobavljač = new HashSet<Narudžba_Dobavljač>();
        }
    
        public int Narudžba_Id { get; set; }
        public int Dobavljač_Id { get; set; }
        public int Plaćanje_Id { get; set; }
        public System.DateTime Datum_Isporuke { get; set; }
        public int Grad_Id { get; set; }
        public int Država_Id { get; set; }
        public bool Izvršena { get; set; }
        public string Ulica { get; set; }
    
        public virtual Dobavljač Dobavljač { get; set; }
        public virtual Država Država { get; set; }
        public virtual Grad Grad { get; set; }
        public virtual Način_Plaćanja Način_Plaćanja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudžba_Dobavljač> Narudžba_Dobavljač { get; set; }
    }
}
