//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pića
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pića()
        {
            this.Količina_Pića = new HashSet<Količina_Pića>();
            this.Narudžba_Dobavljač = new HashSet<Narudžba_Dobavljač>();
            this.Narudžba_Kupac = new HashSet<Narudžba_Kupac>();
        }
    
        public int Piće_Id { get; set; }
        public string Naziv_Pića { get; set; }
        public string Postotak_Alkohola { get; set; }
        public Nullable<int> VrstaPića_Id { get; set; }
        public Nullable<int> Proizvođać_Id { get; set; }
        public string Opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Količina_Pića> Količina_Pića { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudžba_Dobavljač> Narudžba_Dobavljač { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudžba_Kupac> Narudžba_Kupac { get; set; }
        public virtual Proizvođać Proizvođać { get; set; }
        public virtual Vrsta_pića Vrsta_pića { get; set; }
    }
}
