//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Račun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Račun()
        {
            this.Narudžba_Kupac = new HashSet<Narudžba_Kupac>();
        }
    
        public int Račun_Id { get; set; }
        public int Korisnik_Id { get; set; }
        public string Ulica { get; set; }
        public int Grad_Id { get; set; }
        public int Država_Id { get; set; }
        public System.DateTime Datum_Isporuke { get; set; }
        public bool Izvršeno { get; set; }
        public int Plaćanje_Id { get; set; }
    
        public virtual Država Država { get; set; }
        public virtual Grad Grad { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Način_Plaćanja Način_Plaćanja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudžba_Kupac> Narudžba_Kupac { get; set; }
    }
}
