//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dobavljač
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dobavljač()
        {
            this.Narudžba = new HashSet<Narudžba>();
        }
    
        public int Dobavljač_Id { get; set; }
        public string Naziv_dobavljača { get; set; }
        public string Ulica { get; set; }
        public int Grad_Id { get; set; }
        public int Država_Id { get; set; }
        public int Broj_Telefona { get; set; }
        public string Email { get; set; }
        public byte[] Logo { get; set; }
    
        public virtual Država Država { get; set; }
        public virtual Grad Grad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudžba> Narudžba { get; set; }
    }
}
