//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Količina_Pića
    {
        public int Količina_Id { get; set; }
        public int Piće_Id { get; set; }
        public decimal Cijena { get; set; }
    
        public virtual Količina Količina { get; set; }
        public virtual Pića Pića { get; set; }
    }
}
